-- Add frontend marketplace fields to persisted API state.
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "sellerHandle" TEXT;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "rating" DOUBLE PRECISION;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "reviewCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "accent" TEXT;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "icon" TEXT;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "featured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "terms" TEXT;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "deliverablesJson" TEXT;

ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "buyerNote" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "requestSourceText" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "requestReferenceLink" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "requestFileName" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "requestFileSize" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "deliveryFileName" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "deliveryFileSize" TEXT;
